#!/bin/bash
#
# Script        :Add this header to the existing files
# Author        :Dacian Tomus
# Website       :https://github.com/dactom
# Email         : 
# Description   :
# Dependencies  :
# Usage         :
# License       :GPLv3
#
sed -i '/\#\!\/bin\/bash/d' $1
cat header $1 > new_$1
mv new_$1 $1
chmod u+x $1
