#!/bin/bash
#
# Script        :
# Author        :Dacian Tomus
# Website       :https://github.com/dactom
# Email         : 
# Description   :
# Dependencies  :
# Usage         :
# License       :GPLv3
#
rm -rf ./sa*.dat
rm -rf ./sar*.png
for i in 0{1..9} {10..30}
    do
        #Collect data from sar
        file_dat="sa$i.dat"
	sar -f /var/log/sa/sa$i -r | awk 'FNR>3 {print $1 " " ($2+$5+$6)/1024 " " $5/1024 " " $6/1024 " " ($3-$5-$6-$2)/1024     }' > $file_dat
        
        #Start gnuplot
        gnuplot << EOF
        set terminal pngcairo enhanced font 'Verdana,12'
        set output "sar_mem$i.png"
        set title "CPU usage graph"
	set grid xtics lt 0 lw 2 lc rgb "#bbbbbb"
	set grid ytics lt 0 lw 2 lc rgb "#bbbbbb"
        set xrange [0:24]
	set xtics 2
	#set ytics 10
        set yrange [0:28000]
        set xlabel "Time, hrs"
        set ylabel "Memory, MB"
        plot "$file_dat" using 1:2 with lines title "Free" lt 1 lw 2,\
             "$file_dat" using 1:3 with lines title "Buffer" lt 2 lw 2,\
             "$file_dat" using 1:4 with lines title "Cached" lt 3 lw 2,\
             "$file_dat" using 1:4 with lines title "Used" lt 4 lw 2
EOF
    done
