#!/bin/bash
#
# Script        :
# Author        :Dacian Tomus
# Website       :https://github.com/dactom
# Email         : 
# Description   :
# Dependencies  :
# Usage         :
# License       :GPLv3
#
get_date=$( date +%F )
file=$1
file_name=${file%%.*}
name="$file_name"_$get_date""
echo "The file become: $name"
cp $1 $name
