#!/bin/bash
#
# Script        :
# Author        :Dacian Tomus
# Website       :https://github.com/dactom
# Email         : 
# Description   :
# Dependencies  :
# Usage         :
# License       :GPLv3
#
get_date=$( date +%F )
file_name="$get_date"_$1""
echo "The file become: $file_name"
cp $1 $file_name
