#!/bin/bash
max_users=$(cat /etc/passwd | wc -l)
user_id=$(awk -F: '{print $3}' /etc/passwd)
#user_name=$(awk -F: '{print $1}' /etc/passwd)
#echo $max_users $user_id $user_name
for i in $user_id
do
	if [ $i -gt 1000 ]
	then
		user_name_line=$(grep -e "$i" /etc/passwd)
		user_name=$(echo $user_name_line | awk -F: '{print $1}')
		userdel -r $user_name
	fi
done

