#!/bin/bash
#
# Script        :delete_users
# Author        :Dacian Tomus
# Website       :https://github.com/dactom
# Email         : 
# Description   :Delete the users created with add_users
# Dependencies  :
# Usage         :
# License       :GPLv3
#

max_users=$(cat /etc/passwd | wc -l)
user_id=$(awk -F: '{print $3}' /etc/passwd)

for i in $user_id
do
	if [ $i -gt 1000 ]
	then
		user_name_line=$(grep -e "$i" /etc/passwd)
		user_name=$(echo $user_name_line | awk -F: '{print $1}')
		userdel -r $user_name
	fi
done

