#!/bin/bash
#
# Script        :
# Author        :Dacian Tomus
# Website       :https://github.com/dactom
# Email         : 
# Description   :How many words for each alphabet letter
# Dependencies  :
# Usage         :
# License       :GPLv3
#
for i in {a..z}
    do
        count=$(grep -i -e ^$i /usr/share/dict/words | wc -l)
        echo "Number of word starting with letter $i is $count"
    done
