#!/bin/bash
#
# Script        :
# Author        :Dacian Tomus
# Website       :https://github.com/dactom
# Email         : 
# Description   :How may linux commands are with two letter
# Dependencies  :
# Usage         :
# License       :GPLv3
#
for i in {a..z} 
do
    file_name="/bin/$i?"
    name=$(ls $file_name 2>/dev/null)
    if [ $? == 0 ] 
    then
        echo -n "$i - "
        echo "$name" | wc -l
        echo "$name"
    else
        echo "No file with $i"
    fi
done

