#!/bin/bash
sum=0
for i in {1..31}
do
	myvar=$( grep -x ".\{$i\}" /usr/share/dict/words | wc -l)
	echo "Number of words with $i characters is $myvar"
	sum=$(( $myvar + $sum )) 
done
echo "Sum of words is : $sum"
